query BooksQuery {
  entries(section: "books") {
    slug
    title
    ... on books_books_Entry {
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          buttonUrl
          buttonText
          featuredImage {
            title
            filename
          }
          image {
            filename
            title
          }
        }
      }
      featured
    }
  }
}
