query {
  entries(site: "floorFiftyFour",section: "books") {
    slug
    title
    hero {
      heading
      subHeading
      description
      featuredImage {
        title
        filename
      }
      image {
        title
        filename
      }
    }
    featured
  }
}