query BooksQuery($limit: Int) {
  entries(section: "books", limit: $limit) {
    slug
    title
    ... on books_books_Entry {
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          buttonUrl
          buttonText
          featuredImage {
            title
            filename
          }
          image {
            filename
            title
          }
        }
      }
      featured
    }
  }
}
