query item($slug: [String!], $limit: Int) {
    entry (section: "itemsOfInterest", slug: $slug, limit: $limit) {
        id
        title
        ... on itemsOfInterest_itemsOfInterest_Entry {
            id
            slug
            seoTitle
            seoContentType
            seoImage {
                filename
                title
            }
            seoMetaDescription
            seoRobots(label: true)
            hero {
                ... on hero_BlockType {
                    id
                    heading
                    subHeading
                    image {
                        title
                        filename
                    }
                }
            }
            contentField
            assets {
                ... on assets_BlockType {
                    id
                    blockHeading
                    assets {
                        ... on assets_asset_BlockType {
                        id
                        assetItem {
                            filename
                            title
                        }
                        assetDescription
                        }
                    }
                }
            }
            linkFields {
                ... on linkFields_BlockType {
                    id
                    blockHeading
                    linkField {
                        ... on linkField_linkItem_BlockType {
                            id
                            linkLabel
                            itemType
                            itemLink
                        }
                    }
                }
            }
        }
    }
}