query report($slug: [String!]) {
    entry (section: "reports", slug: $slug) {
        id
        ... on reports_reports_Entry {
            seoTitle
            seoContentType
            seoImage {
                filename
                title
            }
            seoMetaDescription
            seoCanonical
            seoRobots(label: true)
            id
            title
            heading
            subheading
            pageBuilder {
                ... on pageBuilder_contentSimple_BlockType {
                    id
                    contentTitle
                    contentCopy
                    typeHandle
                }
                ... on pageBuilder_asset_BlockType {
                id
                imageSize
                image {
                    ... on images_Asset {
                        id
                        filename
                        title
                    }
                }
                typeHandle
                }
            }
        }
    }
}