query book($slug: [String!]) {
    entry (site: "floorFiftyFour",section: "storiesFloorFiftyFour", slug: $slug) {
        id,
        title
        hero {
          heading
          subHeading
        }
        contentField
    }
}