query aboutQuery {
  entry(slug: "about") {
    ... on about_about_Entry {
      id
      seoTitle
      seoCanonical
      seoMetaDescription
      seoMetaKeywords
      seoRobots(label: true)
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          featuredImage {
            title
            filename
          }
          image {
            title
            filename
          }
        }
      }
      pageBuilder {
        ... on pageBuilder_contentSimple_BlockType {
          id
          typeHandle
          contentTitle
          contentCopy
        }
        ... on pageBuilder_asset_BlockType {
          id
          typeHandle
          imageSize
          image {
            filename
            title
          }
        }
      }
    }
  }
}
