query {
  entries(site: "floorFiftyFour",section: "blogOverviewFloorFiftyFour") {
      hero {
        heading
        subHeading
        description
        featuredImage {
          title
          filename
        }
    }
	}
}