query BookOverviewQuery {
  entries(section: "booksOverview") {
    ... on booksOverview_booksOverview_Entry {
      seoTitle
      seoMetaDescription
      seoMetaKeywords
      seoRobots(label: true)
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          featuredImage {
            filename
            title
          }
          image {
            title
            filename
          }
        }
      }
    }
  }
}
