query HomeQuery {
  entries(section: "home") {
    ... on home_home_Entry {
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          featuredImage {
            title
            filename
          }
          image {
            title
            filename
          }
        }
      }
      instafeed {
        ... on instafeed_BlockType {
          id
          instaTitle
          subHeading
          images {
            title
            filename
          }
        }
      }
      seoTitle
      seoMetaDescription
      seoMetaKeywords
      seoRobots(label: true)
    }
  }
}
