query MyQuery {
  entries(section: "shortStoriesOverview") {
    ... on shortStoriesOverview_shortStoriesOverview_Entry {
      id
      hero {
        ... on hero_BlockType {
          id
          heading
          subHeading
          description
          featuredImage {
            filename
            title
          }
        }
      }
    }
  }
}