query MyQuery {
  entries(section: "shortStoriesOverview") {
    ... on shortStoriesOverview_shortStoriesOverview_Entry {
      id
      seoTitle
      seoContentType
      seoImage {
        filename
        title
      }
      seoMetaDescription
      seoCanonical
      seoRobots(label: true)
      hero {
        ... on hero_BlockType {
          id
          heading
          subHeading
          description
          featuredImage {
            filename
            title
          }
        }
      }
    }
  }
}