query BlogArticle($slug: [String!]) {
  entry(slug: $slug) {
    id
    title
    ... on blogArticles_blogArticles_Entry {
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          featuredImage {
            title
            filename
          }
        }
      }
      contentField
      seoContentType
      seoImage {
        filename
        title
      }
      seoMetaDescription
      seoRobots(label: true)
    }
  }
}