query ArticlesQuery {
  entries(section: "blogArticles") {
    slug
    postDate
    ... on blogArticles_blogArticles_Entry {
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          description
          featuredImage {
            title
            filename
          }
        }
      }
    }
  }
}
