query {
  entries(site: "floorFiftyFour",section: "blogFloorFiftyFour") {
      slug
      postDate
      hero {
        heading
        subHeading
        description
        featuredImage {
          title
          filename
        }
    }
	}
}