query book($slug: [String!]) {
    entry (site: "floorFiftyFour",section: "blogFloorFiftyFour", slug: $slug) {
        id,
        title
        hero {
          heading
          subHeading
          copy
        }
    }
}