query StoriesQuery {
  entries(section: "shortStories") {
    ... on shortStories_shortStories_Entry {
      featured
      slug
      hero {
        ... on hero_BlockType {
          heading
          description
          subHeading
          featuredImage {
            filename
            title
          }
        }
      }
    }
    next {
      id
      title
      uri
    }
    prev {
      uri
      title
      id
    }
  }
}
