query BlogArticle($slug: [String!]) {
  entry(slug: $slug) {
    id
    title
    ... on shortStories_shortStories_Entry {
      seoContentType
      seoImage {
        filename
        title
      }
      seoTitle
      seoMetaDescription
      seoRobots(label: true)
      hero {
        ... on hero_BlockType {
          heading
          subHeading
          featuredImage {
            title
            filename
          }
        }
      }
      contentField
      report {
        ... on report_item_BlockType {
          id
          reportLabel
          reportEntry {
            uri
          }
        }
      }
    }
  }
}