query {
  entries(site: "floorFiftyFour",section: "storiesFloorFiftyFour") {
      slug
      featured
      hero {
        heading
        subHeading
        description
        featuredImage {
          title
          filename
        }
    }
	}
}