query GlobalQuery {
  globalSets {
    ... on general_GlobalSet {
      name
      newsletterBanner {
        title
        filename
      }
      imageSingle {
        filename
        title
      }
      seoTitle
      seoImage {
        filename
        title
      }
      seoContentType
      seoCanonical
      seoMetaDescription
      seoRobots
    }
  }
}
